#server:
#  port: 8088
#
#---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: payment
          uri: http://localhost:8081
          predicates:
            - Path=/payments/** 
        - id: blueSquare
          uri: http://localhost:8082
          predicates:
            - Path=/halls/** 
        - id: reservation
          uri: http://localhost:8083
          predicates:
            - Path=/reservations/** 
        - id: message
          uri: http://localhost:8084
          predicates:
            - Path=/messages/** 
        - id: viewpage
          uri: http://localhost:8085
          predicates:
            - Path= /reservationViews/**
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  sleuth:
    propagation-keys: x-request-id,x-ot-span-context
  zipkin:
    base-url: http://jaeger-collector.default.svc.cluster.local:9411
  cloud:
    gateway:
      routes:
        - id: payment
          uri: http://team01-payment:8080
          predicates:
            - Path=/payments/** 
        - id: blueSquare
          uri: http://team01-bluesqure:8080
          predicates:
            - Path=/halls/** 
        - id: reservation
          uri: http://team01-reservation:8080
          predicates:
            - Path=/reservations/** 
        - id: message
          uri: http://team01-message:8080
          predicates:
            - Path=/messages/** 
        - id: viewpage
          uri: http://team01-viewpage:8080
          predicates:
            - Path= /reservationViews/**
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
 
#          - id: payment
#           uri: http://payment:8080
#           predicates:
#             - Path=/payments/** 
#         - id: blueSquare
#           uri: http://blueSquare:8080
#           predicates:
#             - Path=/halls/** 
#         - id: reservation
#           uri: http://reservation:8080
#           predicates:
#             - Path=/reservations/** 
#         - id: message
#           uri: http://message:8080
#           predicates:
#             - Path=/messages/** 
#         - id: viewpage
#           uri: http://viewpage:8080
#           predicates:
#             - Path= /reservationViews/**
#         - id: frontend
#           uri: http://frontend:8080
#           predicates:
#             - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
  

